version: "3.8"

services:
    # I could add mongo as store but it requires more time and i already spent enough
    # store:
    #     image: "mongo:latest"
    #     container_name: scraper-store
    #     ports:
    #         - "27017:27017"
    #     volumes: 
    #         - cache:/data
        

    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: scraper-app
        privileged: true
        ports:
            - "8080:8080"
        environment:
            PORT: 8080
        # depends_on:
        #     - store
# volumes:
#   cache:
#     driver: local
